image: Visual Studio 2017

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  - ps: $urlCurrent = "https://download.visualstudio.microsoft.com/download/pr/ac85ccb0-e761-489f-b5dd-ba5e52735c2b/dd89fcc72092ff6fc7f5f4cb9eea0de4/dotnet-sdk-3.1.200-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement src\BundlerMinifier.Core\Constants.cs 'VERSION = "([0-9\\.]+)"' 'VERSION = "{version}"'

build_script:
  - dotnet restore BundlerMinifier.sln
  - nuget restore .\src\BundlerMinifierVSIX -Verbosity quiet -PackagesDirectory .\Packages
  - msbuild .\src\BundlerMinifierConsole\BundlerMinifierConsole.csproj /p:configuration=Release /v:m
  - msbuild .\src\BundlerMinifierVSIX\BundlerMinifierVSIX.csproj /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  - msbuild .\src\BundlerMinifierTest\BundlerMinifierTest.csproj /p:configuration=Release /v:m
  - ps: dotnet pack src\BundlerMinifier\ -c Release "/p:Version=${env:APPVEYOR_BUILD_VERSION}"
  - ps: dotnet pack src\BundlerMinifier.Core\ -c Release "/p:Version=${env:APPVEYOR_BUILD_VERSION}"
  - ps: dotnet pack src\BundlerMinifier.TagHelpers\ -c Release "/p:Version=${env:APPVEYOR_BUILD_VERSION}"

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery .\src\BundlerMinifierVsix\**\*.vsix

artifacts:
  - path: src\**\*.nupkg
    name: NuGet package

before_deploy:
  - ps: Vsix-CreateChocolatyPackage -packageId bundlerminifier

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/

  - provider: Environment
    name: Chocolatey
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/
